### ISSUE TITLE
Cannot run on current directory

### ISSUE THREAD

**Issue by chocol4te** [io12/unf#1]
I get the following error when I try and run `unf` on the current directory. Moving up a layer and running on the folder works fine.

```bash
$ unf -rf .
unf: error: path '.' has no basename
```

**Comment by io12** [comment]
Sorry I didn't see this issue earlier. For some reason, GitHub had this repo unwatched for me so I didn't get a notification. Working on this now.

**Comment by io12** [comment]
Thanks for the issue! Fixed!
